LoginAndRegister/LoginAndRegister/Controllers/FirstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginAndRegister.Controllers
{
    public class FirstController : Controller
    {
        // GET: First
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            ViewBag.LoginState = "登陆前...";
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection formCollection)
        {
            string email = formCollection["inputEmail3"];
            string password = formCollection["inputPassword3"];

            ViewBag.LoginState =email+ "登陆后...";
            return View();
        }
    }

}

LoginAndRegister/LoginAndRegister/Views/First/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div>
    <p>Hello MVC!!</p>
</div>

LoginAndRegister/LoginAndRegister/Views/First/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<!--<h2>Login</h2>-->
    <div>
        <div id="LoginState">
            @ViewBag.LoginState
        </div>
        @using (Html.BeginForm("Login", "First", FormMethod.Post, new { @class = "form-horizontal" }))
        {
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" name="inputEmail3" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="inputPassword3" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Remember me
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Sign in</button>
                    </div>
                </div>
                }
        </div>

LoginAndRegister/LoginAndRegister/Views/First/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>